layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 100
  exclude:
    forks: true
    projects:
     - repo-name

social_media:
  # behance: your_username
  facebook: mohammed.elnaggar69
  # dribbble: your_username
  linkedin: moelnaggar14
  stackoverflow: 10739162
  twitter: moelnaggar14
  # youtube: your_username

topics:
  - name: Swift
    web_url: https://github.com/topics/swift
    image_url: https://raw.githubusercontent.com/github/explore/8fb8b0e9d61d266721825ce116060773ea2503c2/topics/swift/swift.png
  
  - name: iOS Development
  
  - name: Realm IO
    web_url: https://github.com/realm
    image_url: https://avatars1.githubusercontent.com/u/7575099?s=200&v=4
  
  - name: RxSwift
    web_url: https://github.com/ReactiveX/RxSwift
    image_url: https://avatars3.githubusercontent.com/u/6407041?s=200&v=4
  
  - name: fastlane
    web_url: https://github.com/fastlane
    image_url: https://avatars2.githubusercontent.com/u/11098337?s=200&v=4
  
  - name: App Architecture
    web_url: https://github.com/objcio/app-architecture
    image_url: https://avatars3.githubusercontent.com/u/4409139?s=200&v=4
  
  - name: swift Algorithm Club
    web_url: https://github.com/raywenderlich/swift-algorithm-club
    image_url: https://avatars3.githubusercontent.com/u/4722515?s=200&v=4
  
  - name: Git "GitFlow"
    web_url: https://git-scm.com
    image_url: https://git-scm.com/images/logos/downloads/Git-Logo-2Color.png 
    
